POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
     "title": "10 Tips for Effective Project Management in 2024",
     "author": "John Davis",
     "url": "https://www.example.com/effective-project-management-tips",
     "likes": 1203
} 
