PUT http://localhost:3003/api/blogs/6602f73f4fd495fe43a3cdea HTTP/1.1
content-type: application/json  

{
     "title": "React patterns 2",
     "author": "Michael Chan",
     "url": "https://www.example.com/effective-project-management-tips-2",
     "likes": 9
} 
